config/routes.rb
Rails.application.routes.draw do

  get 'mycart/index'

  resources :food_items
  get 'menu/index'


 root 'home#index'

 get 'contact_us' => 'home#contact_us'
 get 'menu' => 'menu#index'
 get 'mycart' => 'mycart#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord

  mount_uploader :image, FoodItemImageUploader

  def image_url_or_auto
    if image_url.present?
      image_url
    else
      "http://loremflickr.com/320/240/brazil,rio/#{name}"
    end

  end


   def self.filter_by_section(section)
     where(section: section)
   end

  end

app/models/user.rb
class User < ApplicationRecord


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]

  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :description, :price, :section, :image_url)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end



def contact_us

end

end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
    @section = %w(Breakfast Lunch Dinner Supper)

    @food_items =FoodItem.filter_by_section(params[:section])
  end
end

app/controllers/mycart_controller.rb
class MycartController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/mycart_helper.rb
module MycartHelper
end

app/views/food_items/_form.html.erb
<%= simple_form_for(@food_item) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :section %>
    <%= f.input :image_url %>

    <%= f.input :image, as: :file %>
</div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Food Items</h1>

<table class = "table table-bordered table-striped">
  <thead class = "thead thead-default">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Section</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.description %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.section %></td>
        <td><%= image_tag food_item.image_url_or_auto %></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
       <td> <%= link_to "Add to Cart", :controller => :mycart, :action => :index %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food Item', new_food_item_path %>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food_item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @food_item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food_item.price %>
</p>

<p>
  <strong>Section:</strong>
  <%= @food_item.section %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @food_item.image_url %>
</p>

<%= link_to 'Edit', edit_food_item_path(@food_item) %> |
<%= link_to 'Back', food_items_path %>

app/views/home/contact_us.html.erb
<div class = "col-sm-4">
  <h2> Address </h2>
  <address class = "address">
    123 melbourne
  </address>
</div>


<div class = "col-sm-8">
  <h2> Map </h2>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3161.5258881389527!2d144.91338921499627!3d-37.58978047979357!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ad653d569791587%3A0x4b34be9667318ee7!2s7%2F1-27+Punt+St%2C+Craigieburn+VIC+3064!5e0!3m2!1sen!2sau!4v1482833276979" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
  </address>
</div>


<div class="container">
  <form id="contact" action="" method="post">
    <h2>Rohit's Food Truck Contact Form</h2>
    <h4>Contact us for custom quote</h4>
    <fieldset>
      <input placeholder="Your name" type="text" tabindex="1" required autofocus>
    </fieldset>
    <fieldset>
      <input placeholder="Your Email Address" type="email" tabindex="2" required>
    </fieldset>
    <fieldset>
      <input placeholder="Your Phone Number (optional)" type="tel" tabindex="3" required>
    </fieldset>
    <fieldset>
      <textarea placeholder="Type your message here...." tabindex="5" required></textarea>
    </fieldset>
    <fieldset>
      <button name="submit" type="submit" id="contact-submit" data-submit="...Sending">Submit</button>

  </form>
</div>

app/views/layouts/_header.html.erb
<div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "AMBROSIAL", root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Products", products_path %></li>

           <% if current_user %>


             <li><%= link_to "Dashboard", dashboard_path %></li>
             <li><%= link_to "Settings", edit_user_registration_path %></li>

              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %>

           <% else %>

             <li><%= link_to "Login", new_user_session_path %></li>

           <% end %>


          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challengehub</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1> <strong>Welcome to Rohit's Food Truck </strong></h1>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <li><%= link_to "Rohit's food Truck", root_path %></li>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "Menu", menu_path %></li>
            <li><%= link_to "Contact Us", contact_us_path %></li>

          </ul>
          <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
             <li><%= link_to "Login", new_user_session_path %></li>
             <li><%= link_to "Sign Up", new_user_registration_path %></li>

               <li><%= link_to "Logout", destroy_user_session_path, method: :delete %>


            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>


    <%= yield %>
  </body>
</html>

app/views/menu/index.html.erb
<h1>Menu</h1>


<ul class = "nav nav-pills">

   <% @section.each do |section| %>
   <li class = "nav-item">

      <%= link_to section, menu_path(section: section), class: "nav-link #{params[:section] == section ? 'active' : ''}" %>
      <% end %>
</li>
</ul>

<% @food_items.each do |item| %>
<div class = "card">
  <div class = "card-block">
   <%= item.name %>
 </div>

 <div class = "card-block">

    <%= image_tag item.image_url %>
  </div>

</div>
<% end %>

app/views/mycart/index.html.erb
<h1>Mycart#index</h1>
<p>Find me in app/views/mycart/index.html.erb</p>